-- ROTA EXPRESS - ATUALIZAÇÃO COMPLETA
-- Rode este SQL no Supabase > SQL Editor antes de usar a nova versão.

-- Campos extras na tabela usuarios
alter table if exists public.usuarios
  add column if not exists ativo boolean default true;

-- Campos extras na tabela pedidos
alter table if exists public.pedidos
  add column if not exists mp_payment_id text,
  add column if not exists pagamento_status text default 'Aguardando confirmação',
  add column if not exists liberado boolean default false,
  add column if not exists pago_motoboy boolean default false,
  add column if not exists data_pagamento text,
  add column if not exists data_finalizacao text;


-- Campos separados de endereço na tabela pedidos
alter table if exists public.pedidos
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;

-- Histórico de entregas finalizadas
create table if not exists public.historico_entregas (
  id bigint generated by default as identity primary key,
  pedido_id bigint,
  cliente_nome text,
  motoboy_id bigint,
  motoboy_nome text,
  coleta text,
  entrega text,
  valor numeric default 0,
  km numeric default 0,
  finalizado_em text,
  criado_em timestamp with time zone default now()
);

-- Histórico de pagamentos dos motoboys
create table if not exists public.historico_pagamentos (
  id bigint generated by default as identity primary key,
  motoboy_id bigint,
  motoboy_nome text,
  valor_pago numeric default 0,
  valor_bruto numeric default 0,
  taxa_rota numeric default 20,
  pedidos_ids jsonb,
  pago_em text,
  criado_em timestamp with time zone default now()
);

-- Caso use RLS, libere as políticas conforme sua regra de segurança.
-- Para teste rápido, o sistema funciona melhor com RLS desativado nas tabelas:
-- usuarios, pedidos, historico_entregas e historico_pagamentos.


-- Campos separados de endereço no histórico de entregas
alter table if exists public.historico_entregas
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;
