-- ROTA EXPRESS - ATUALIZAÇÃO COMPLETA
-- Rode este SQL no Supabase > SQL Editor antes de usar a nova versão.

-- Campos extras na tabela usuarios
alter table if exists public.usuarios
  add column if not exists ativo boolean default true;

-- Campos extras na tabela pedidos
alter table if exists public.pedidos
  add column if not exists mp_payment_id text,
  add column if not exists data_finalizacao text;


-- Campos separados de endereço na tabela pedidos
alter table if exists public.pedidos
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;

-- Histórico de entregas finalizadas
create table if not exists public.historico_entregas (
  id bigint generated by default as identity primary key,
  pedido_id bigint,
  cliente_nome text,
  motoboy_id bigint,
  motoboy_nome text,
  coleta text,
  entrega text,
  valor numeric default 0,
  km numeric default 0,
  finalizado_em text,
  criado_em timestamp with time zone default now()
);

-- Histórico de pagamentos dos motoboys
create table if not exists public.historico_pagamentos (
  id bigint generated by default as identity primary key,
  motoboy_id bigint,
  motoboy_nome text,
  valor_pago numeric default 0,
  valor_bruto numeric default 0,
  taxa_rota numeric default 20,
  pedidos_ids jsonb,
  pago_em text,
  criado_em timestamp with time zone default now()
);

-- Caso use RLS, libere as políticas conforme sua regra de segurança.
-- Para teste rápido, o sistema funciona melhor com RLS desativado nas tabelas:
-- usuarios, pedidos, historico_entregas e historico_pagamentos.


-- Campos separados de endereço no histórico de entregas
alter table if exists public.historico_entregas
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;

-- Correção para o saldo do motoboy no histórico
alter table if exists public.historico_entregas
  add column if not exists pago_motoboy boolean default false,
  add column if not exists data_pagamento text;

alter table if exists public.pedidos
  add column if not exists data_pagamento text;

-- Correção extra: garante que pedidos finalizados antigos apareçam no saldo do motoboy
update public.pedidos
set pago_motoboy = false
where pago_motoboy is null;

insert into public.historico_entregas (
  pedido_id, cliente_nome, motoboy_id, motoboy_nome,
  coleta, coleta_cidade, coleta_bairro, coleta_rua,
  entrega, entrega_cidade, entrega_bairro, entrega_rua,
  valor, km, finalizado_em, pago_motoboy
)
select
  p.id, p.cliente_nome, p.motoboy_id, p.motoboy_nome,
  coalesce(p.coleta, ''), coalesce(p.coleta_cidade, ''), coalesce(p.coleta_bairro, ''), coalesce(p.coleta_rua, ''),
  coalesce(p.entrega, ''), coalesce(p.entrega_cidade, ''), coalesce(p.entrega_bairro, ''), coalesce(p.entrega_rua, ''),
  coalesce(p.valor, 0), coalesce(p.km, 0), coalesce(p.data_finalizacao, ''), coalesce(p.pago_motoboy, false)
from public.pedidos p
where lower(coalesce(p.status, '')) like '%finaliz%'
  and not exists (
    select 1 from public.historico_entregas h where h.pedido_id = p.id
  );


-- Reforço para Histórico de pagamentos: garante todas as colunas usadas pelo sistema
alter table if exists public.historico_pagamentos
  add column if not exists motoboy_id bigint,
  add column if not exists motoboy_nome text,
  add column if not exists valor_pago numeric default 0,
  add column if not exists valor_bruto numeric default 0,
  add column if not exists taxa_rota numeric default 20,
  add column if not exists pedidos_ids jsonb,
  add column if not exists pago_em text,
  add column if not exists criado_em timestamp with time zone default now();

-- Garante campos de pagamento nos pedidos/histórico de entregas
alter table if exists public.pedidos
  add column if not exists pago_motoboy boolean default false,
  add column if not exists data_pagamento text;

alter table if exists public.historico_entregas
  add column if not exists pago_motoboy boolean default false,
  add column if not exists data_pagamento text;

-- CORREÇÃO DO ERRO: new row violates row-level security policy for table "historico_pagamentos"
-- Libera leitura/escrita do histórico de pagamentos para o sistema atual.
alter table if exists public.historico_pagamentos disable row level security;
alter table if exists public.historico_entregas disable row level security;
alter table if exists public.pedidos disable row level security;
alter table if exists public.usuarios disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.historico_pagamentos to anon, authenticated;
grant select, insert, update, delete on public.historico_entregas to anon, authenticated;
grant select, insert, update, delete on public.pedidos to anon, authenticated;
grant select, insert, update, delete on public.usuarios to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;


-- CORREÇÃO DEFINITIVA RLS HISTÓRICO PAGAMENTOS
-- Rode no Supabase > SQL Editor. Corrige o erro:
-- new row violates row-level security policy for table "historico_pagamentos"

create table if not exists public.historico_pagamentos (
  id bigint generated by default as identity primary key,
  motoboy_id bigint,
  motoboy_nome text,
  valor_pago numeric default 0,
  valor_bruto numeric default 0,
  taxa_rota numeric default 20,
  pedidos_ids jsonb,
  pago_em text,
  criado_em timestamp with time zone default now()
);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.historico_pagamentos to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.historico_pagamentos enable row level security;

drop policy if exists "historico_pagamentos_select_all" on public.historico_pagamentos;
drop policy if exists "historico_pagamentos_insert_all" on public.historico_pagamentos;
drop policy if exists "historico_pagamentos_update_all" on public.historico_pagamentos;
drop policy if exists "historico_pagamentos_delete_all" on public.historico_pagamentos;

create policy "historico_pagamentos_select_all"
  on public.historico_pagamentos for select
  to anon, authenticated
  using (true);

create policy "historico_pagamentos_insert_all"
  on public.historico_pagamentos for insert
  to anon, authenticated
  with check (true);

create policy "historico_pagamentos_update_all"
  on public.historico_pagamentos for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "historico_pagamentos_delete_all"
  on public.historico_pagamentos for delete
  to anon, authenticated
  using (true);


-- PIX AUTOMÁTICO
-- Garante que o sistema consiga atualizar o pedido automaticamente quando o Mercado Pago confirmar o Pix.
alter table if exists public.pedidos disable row level security;

-- Status padrão usado a partir desta versão:
-- 1) Aguardando pagamento Pix
-- 2) Pix confirmado + Liberado para motoboys
-- 3) Aceito pelo motoboy / Pedido coletado / Entrega finalizada

-- Notificações no celular dos motoboys
alter table if exists public.usuarios
  add column if not exists push_subscription jsonb;

-- Necessário para salvar a permissão de notificação do motoboy
alter table if exists public.usuarios disable row level security;
