-- ROTA EXPRESS - ATUALIZAÇÃO COMPLETA
-- Rode este SQL no Supabase > SQL Editor antes de usar a nova versão.

-- Campos extras na tabela usuarios
alter table if exists public.usuarios
  add column if not exists ativo boolean default true;

-- Campos extras na tabela pedidos
alter table if exists public.pedidos
  add column if not exists mp_payment_id text,
  add column if not exists data_finalizacao text;


-- Campos separados de endereço na tabela pedidos
alter table if exists public.pedidos
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;

-- Histórico de entregas finalizadas
create table if not exists public.historico_entregas (
  id bigint generated by default as identity primary key,
  pedido_id bigint,
  cliente_nome text,
  motoboy_id bigint,
  motoboy_nome text,
  coleta text,
  entrega text,
  valor numeric default 0,
  km numeric default 0,
  finalizado_em text,
  criado_em timestamp with time zone default now()
);

-- Histórico de pagamentos dos motoboys
create table if not exists public.historico_pagamentos (
  id bigint generated by default as identity primary key,
  motoboy_id bigint,
  motoboy_nome text,
  valor_pago numeric default 0,
  valor_bruto numeric default 0,
  taxa_rota numeric default 20,
  pedidos_ids jsonb,
  pago_em text,
  criado_em timestamp with time zone default now()
);

-- Caso use RLS, libere as políticas conforme sua regra de segurança.
-- Para teste rápido, o sistema funciona melhor com RLS desativado nas tabelas:
-- usuarios, pedidos, historico_entregas e historico_pagamentos.


-- Campos separados de endereço no histórico de entregas
alter table if exists public.historico_entregas
  add column if not exists coleta_cidade text,
  add column if not exists coleta_bairro text,
  add column if not exists coleta_rua text,
  add column if not exists entrega_cidade text,
  add column if not exists entrega_bairro text,
  add column if not exists entrega_rua text;

-- Correção para o saldo do motoboy no histórico
alter table if exists public.historico_entregas
  add column if not exists pago_motoboy boolean default false,
  add column if not exists data_pagamento text;

alter table if exists public.pedidos
  add column if not exists data_pagamento text;

-- Correção extra: garante que pedidos finalizados antigos apareçam no saldo do motoboy
update public.pedidos
set pago_motoboy = false
where pago_motoboy is null;

insert into public.historico_entregas (
  pedido_id, cliente_nome, motoboy_id, motoboy_nome,
  coleta, coleta_cidade, coleta_bairro, coleta_rua,
  entrega, entrega_cidade, entrega_bairro, entrega_rua,
  valor, km, finalizado_em, pago_motoboy
)
select
  p.id, p.cliente_nome, p.motoboy_id, p.motoboy_nome,
  coalesce(p.coleta, ''), coalesce(p.coleta_cidade, ''), coalesce(p.coleta_bairro, ''), coalesce(p.coleta_rua, ''),
  coalesce(p.entrega, ''), coalesce(p.entrega_cidade, ''), coalesce(p.entrega_bairro, ''), coalesce(p.entrega_rua, ''),
  coalesce(p.valor, 0), coalesce(p.km, 0), coalesce(p.data_finalizacao, ''), coalesce(p.pago_motoboy, false)
from public.pedidos p
where lower(coalesce(p.status, '')) like '%finaliz%'
  and not exists (
    select 1 from public.historico_entregas h where h.pedido_id = p.id
  );
